dataset_name: default
dataset_path: TheFinAI/DOLFIN_test
output_type: generate_until
doc_to_target: '{{answer}}'
doc_to_text: '{{query}}'
fewshot_split: train
should_decontaminate: true
doc_to_decontamination_query: "{{query}}"
generation_kwargs:
  do_sample: false
  temperature: 0.0
  max_gen_toks: 512
metric_list:
  - metric: COMET
    aggregation: mean
    higher_is_better: true
metadata:
  version: '1.0'
task: DoLFin
tag: mfb
test_split: test
training_split: train
process_results: !function multifinben_utils.get_comet_score
