dataset_name: default
dataset_path: TheFinAI/jp-chABSA
output_type: generate_until
doc_to_target: polarity
doc_to_text: "{{sentence}} (Target: {{target}})"
fewshot_split: train
should_decontaminate: true
doc_to_decontamination_query: "{{sentence}} (Target: {{target}})"
generation_kwargs:
  until:
    - "."
    - ","
  do_sample: false
  temperature: 0.0
  max_gen_toks: 30
filter_list:
  - name: "score-first"
    filter:
      - function: "regex"
        regex_pattern: "(positive|negative|neutral)"
      - function: "take_first"
metric_list:
  - metric: exact_match
    aggregation: mean
    higher_is_better: true
  - metric: f1
    higher_is_better: true
    aggregation: !function jp_utils.macro_f1_score 
metadata:
  version: '1.0'
task: JPchABSA_gen
tag: jp_gen
test_split: train
training_split: train
