dataset_name: default
dataset_path: TheFinAI/jp-chABSA
output_type: multiple_choice
doc_to_choice: ["positive", "negative", "neutral"]
doc_to_target: polarity
doc_to_text: "{{sentence}} (Target: {{target}})"
fewshot_split: train
should_decontaminate: true
doc_to_decontamination_query: "{{sentence}} (Target: {{target}})"
generation_kwargs:
  do_sample: false
  temperature: 0.0
  max_gen_toks: 10
metric_list:
  - metric: acc
    aggregation: mean
    higher_is_better: true
  - metric: f1
    higher_is_better: true
    aggregation: !function jp_utils.macro_f1_score 
metadata:
  version: '1.0'
task: JPchABSA
tag: jp
test_split: train
training_split: train
